# Generated by Django 5.2.5 on 2025-08-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность клиента')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='client_reviews/', verbose_name='Фото клиента')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.CharField(editable=False, max_length=255, verbose_name='Название услуги')),
                ('task', models.TextField(blank=True, verbose_name='Задача')),
                ('cover', models.ImageField(upload_to='projects/covers/', verbose_name='Обложка')),
                ('large_photo_1', models.ImageField(blank=True, null=True, upload_to='projects/large_photos/', verbose_name='Фото большое 1')),
                ('large_photo_2', models.ImageField(blank=True, null=True, upload_to='projects/large_photos/', verbose_name='Фото большое 2')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('heading_1', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 1')),
                ('text_1', models.TextField(blank=True, verbose_name='Текст 1')),
                ('heading_2', models.CharField(blank=True, max_length=255, verbose_name='Заголовок 2')),
                ('text_2', models.TextField(blank=True, verbose_name='Текст 2')),
                ('client_review_text', models.TextField(blank=True, verbose_name='Отзыв клиента')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('client_position', models.CharField(blank=True, max_length=255, verbose_name='Должность клиента')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='projects/clients/', verbose_name='Фото клиента')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Фото галереи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='data.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='projects/results/', verbose_name='Фото')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Результат проекта',
                'verbose_name_plural': 'Результаты проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.CharField(editable=False, max_length=255, verbose_name='Название услуги')),
                ('cover', models.ImageField(upload_to='services/covers/', verbose_name='Обложка')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('production_time', models.TextField(blank=True, verbose_name='Сроки изготовления')),
                ('heading_1', models.TextField(blank=True, verbose_name='Заголовок 1')),
                ('target_audience', models.TextField(blank=True, verbose_name='Для кого')),
                ('recommendation', models.TextField(blank=True, verbose_name='Рекомендация')),
                ('heading_implementation', models.TextField(blank=True, verbose_name="Заголовок 'Реализация'")),
                ('large_photo', models.ImageField(blank=True, null=True, upload_to='services/large_photos/', verbose_name='Фото большое')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('projects', models.ManyToManyField(blank=True, related_name='services_attached', to='data.project', verbose_name='Прикрепленные проекты')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='data.service', verbose_name='Связанные услуги'),
        ),
    ]
