# Generated by Django 5.2.5 on 2025-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='large_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='services/large_photos/', verbose_name='Фото большое 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='large_photo',
            field=models.ImageField(blank=True, null=True, upload_to='services/large_photos/', verbose_name='Фото большое 1'),
        ),
    ]
