# Generated by Django 5.2.5 on 2025-08-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_service_large_photo_1_alter_service_large_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Материал')),
                ('text1', models.TextField(verbose_name='Результат работы')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='variants',
            field=models.ManyToManyField(blank=True, to='data.variant'),
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.variant')),
            ],
        ),
    ]
