# Generated by Django 5.2.5 on 2025-08-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_variant_service_variants_variantoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantoption',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='data.variant'),
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/gallery/', verbose_name='Фото галереи')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.service', verbose_name='Проект')),
            ],
        ),
    ]
