# Generated by Django 5.2.5 on 2025-08-19 09:22

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_variantoption_variant_servicegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[470, 315], upload_to='news/images', verbose_name='Картинка превью')),
                ('image_top', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 450], upload_to='news/images', verbose_name='Картинка вверху статьи (1080x450)')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('content_editor', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order_num',),
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='services/variant/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='news/images', verbose_name='Картинка')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.newsitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery1/', verbose_name='Фото галереи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images1', to='data.project', verbose_name='Проект')),
            ],
        ),
    ]
