# Generated by Django 5.2.5 on 2025-08-19 09:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_newsitem_variant_cover_image_projectgalleryimage1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'verbose_name_plural': 'Галерея вниз'},
        ),
        migrations.AlterModelOptions(
            name='projectgalleryimage1',
            options={'verbose_name_plural': 'Галерея дополнительная'},
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='content_editor',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='image_top',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='cover',
            field=models.ImageField(null=True, upload_to='news/images', verbose_name='Картинка превью'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор'),
        ),
    ]
