# Generated by Django 5.2.5 on 2025-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_projectgalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
