# Generated by Django 5.2.5 on 2025-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_newsitem_show_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
