# Generated by Django 5.2.5 on 2025-08-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_callbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='large_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/large_photos/', verbose_name='Фото большое 3'),
        ),
    ]
