# Generated by Django 5.2.5 on 2025-08-31 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_project_large_photo_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cover',
        ),
        migrations.CreateModel(
            name='ServiceSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/gallery/', verbose_name='Фото слайдера')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='data.service', verbose_name='Проект')),
            ],
        ),
    ]
