# Generated by Django 5.2.5 on 2025-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_service_cover_servicesliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recommendation_title',
            field=models.TextField(blank=True, verbose_name='Рекомендация заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='target_audience_title',
            field=models.TextField(blank=True, verbose_name='Для кого заголовок'),
        ),
    ]
