# Generated by Django 5.2.5 on 2025-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_service_recommendation_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/gallery/', verbose_name='Фото галереи на главной')),
            ],
        ),
    ]
