# Generated by Django 5.2.5 on 2025-10-20 08:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_homegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='HTML контент'),
        ),
        migrations.AddField(
            model_name='project',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='project',
            name='page_title',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE'),
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='HTML контент'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_title',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE'),
        ),
    ]
