# Generated by Django 5.2.5 on 2025-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_project_content_project_page_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Уникальный путь страницы (например: 'about' или 'contacts')", unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO для страницы',
                'verbose_name_plural': 'SEO страницы',
            },
        ),
    ]
