# Generated by Django 5.2.5 on 2025-10-25 06:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_seopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
