# Generated by Django 5.2.5 on 2025-10-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_seopage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
