# Generated by Django 5.2.5 on 2025-10-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_seopage_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='slug',
            field=models.CharField(help_text="Уникальный путь страницы (например: 'about' или 'contacts')", max_length=255, unique=True),
        ),
    ]
