# Generated by Django 5.2.5 on 2025-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_seopage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='page_title',
            field=models.TextField(blank=True, null=True, verbose_name='TITLE'),
        ),
    ]
