# Generated by Django 6.0.2 on 2026-05-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_newsitem_page_description_newsitem_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heading_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='heading_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Теги через запятую'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_3',
            field=models.TextField(blank=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_4',
            field=models.TextField(blank=True, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='service',
            name='heading_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='heading_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок 4'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Теги через запятую'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_3',
            field=models.TextField(blank=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_4',
            field=models.TextField(blank=True, verbose_name='Текст 4'),
        ),
    ]
